// -*- mode: c++ -*-
// 
// File pca.C generated by TPrincipal::MakeCode
// on Thu Aug 29 02:12:24 2019
// ROOT version 6.18/03
//
// This file contains the functions 
//
//    void  X2P(Double_t *x, Double_t *p); 
//    void  P2X(Double_t *p, Double_t *x, Int_t nTest);
//
// The first for transforming original data x in 
// pattern space, to principal components p in 
// feature space. The second function is for the
// inverse transformation, but using only nTest
// of the principal components in the expansion
// 
// See TPrincipal class documentation for more information 
// 
#ifndef __CINT__
#include <Rtypes.h> // needed for Double_t etc
#endif

//
// Static data variables
//
static Int_t    gNVariables = 10;

// Assignment of eigenvector matrix.
// Elements are stored row-wise, that is
//    M[i][j] = e[i * nVariables + j] 
// where i and j are zero-based
static Double_t gEigenVectors[] = {
  0.092981,
  0.0183025,
  -0.469673,
  0.447794,
  0.337217,
  0.576659,
  0.303622,
  0.163921,
  -0.0395451,
  0.0551067,
  0.300488,
  0.173086,
  -0.0708037,
  0.244314,
  -0.400902,
  0.105924,
  -0.623148,
  0.466415,
  -0.11252,
  0.156799,
  0.208504,
  -0.00193196,
  -0.189206,
  -0.393711,
  0.708482,
  -0.275614,
  -0.247156,
  0.32893,
  -0.0793528,
  0.110579,
  0.101939,
  0.171081,
  -0.2769,
  0.390707,
  -0.127222,
  -0.732616,
  0.382711,
  0.164348,
  -0.0396483,
  0.0552505,
  0.291416,
  0.18814,
  0.474855,
  -0.276517,
  -0.10788,
  0.176643,
  0.534345,
  0.461423,
  -0.111316,
  0.155121,
  0.131793,
  -0.880938,
  0.15007,
  0.180274,
  -0.0199821,
  -0.0784678,
  0.0336452,
  0.196066,
  -0.288921,
  -0.148168,
  0.0399807,
  -0.169596,
  -0.637252,
  -0.56285,
  -0.435647,
  0.0751499,
  0.155583,
  -0.00545381,
  -0.153334,
  0.0597144,
  0.500682,
  -0.143895,
  -0.0635903,
  -0.0454421,
  -0.0563623,
  0.000875005,
  0.0283942,
  0.0280789,
  0.789438,
  -0.307439,
  0.503213,
  -0.113272,
  0.0614414,
  0.0652156,
  0.0288443,
  -0.0140081,
  -0.00186302,
  -0.5194,
  -0.0484328,
  0.672877,
  0.489283,
  0.258237,
  0.00176374,
  -0.00720891,
  0.0399618,
  0.0187477,
  -0.016582,
  -0.313741,
  -0.482671,
  -0.600193};

// Assignment to eigen value vector. Zero-based.
static Double_t gEigenValues[] = {
  0.385574,
  0.111974,
  0.103131,
  0.102198,
  0.0999811,
  0.0992024,
  0.0979399,
  1.39133e-16,
  2.70742e-16,
  5.38836e-16
};

// Assignment to mean value vector. Zero-based.
static Double_t gMeanValues[] = {
  4.99425,
  8.0105,
  2.017,
  4.9975,
  8.0189,
  1.97633,
  4.99577,
  35.0103,
  30.0145,
  28.0382
};

// Assignment to sigma value vector. Zero-based.
static Double_t gSigmaValues[] = {
  0.992626,
  2.82439,
  1.99185,
  0.995217,
  2.79416,
  2.00942,
  0.999632,
  5.1466,
  5.04129,
  4.64356
};

// 
// The function   void X2P(Double_t *x, Double_t *p)
// 
void X2P(Double_t *x, Double_t *p) {
  for (Int_t i = 0; i < gNVariables; i++) {
    p[i] = 0;
    for (Int_t j = 0; j < gNVariables; j++)
      p[i] += (x[j] - gMeanValues[j]) 
        * gEigenVectors[j *  gNVariables + i] / gSigmaValues[j];

  }
}

// 
// The function   void P2X(Double_t *p, Double_t *x, Int_t nTest)
// 
void P2X(Double_t *p, Double_t *x, Int_t nTest) {
  for (Int_t i = 0; i < gNVariables; i++) {
    x[i] = gMeanValues[i];
    for (Int_t j = 0; j < nTest; j++)
      x[i] += p[j] * gSigmaValues[i] 
        * gEigenVectors[i *  gNVariables + j];
  }
}

// EOF for pca.C
